eshop_user_homepage:
    path:     /
    defaults: { _controller: EshopUserBundle:Default:index }
eshop_user_login:
    path:     /login1
    defaults: { _controller: EshopUserBundle:Default:login }
eshop_user_acceuil:
    path:     /acceuilAdmin
    defaults: { _controller: EshopUserBundle:Admin:acceuil }