
eshop_client_compteClient:
    path:     /compteClient
    defaults: { _controller: EshopClientBundle:CompteClient:compteClient }
eshop_client_acceuilConecter:
    path:     /acceuilConnecter
    defaults: { _controller: EshopClientBundle:CompteClient:acceuilConnecter }
